# SPDX-FileCopyrightText: 2025 LibreCode coop and contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
version = 1
SPDX-PackageName = "3rdparty"
SPDX-PackageSupplier = "LibreCode <contact@librecode.coop>"
SPDX-PackageDownloadLocation = "https://github.com/LibreSign/3rdparty/"

default-license = "AGPL-3.0-or-later"
default-copyright = "2025 LibreCode coop and contributors"

[[annotations]]
path = ".github/CODEOWNERS"
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
    "vendor-bin/**/composer.json",
    "vendor-bin/**/composer.lock"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 LibreCode coop and contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "composer/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"

